import { Selector } from 'testcafe';

export default {
  codeName: Selector('[name="code"]'),
  discountItemLink: Selector('[href*="DiscountItem"]'),
  discountCodeField: Selector('[name="code"]'),
  discountLinkResponsive: Selector('.tdText a').nth(3),
  dummyDiscountGeneratorButton: Selector('.group.noToggler.left > .button.button-green').nth(0),
  firstOrderNumberInResultTable: Selector(
    '.resultSet:nth-child(2) tbody tr:nth-child(1) td:nth-child(4) a',
  ),
  logInButton: Selector('.btn-success'),
  mailShortConnectionInfo: Selector('.viTripWithShortConnectionTimeNotification'),
  mailSelfTransferInfo: Selector('.tripInformationItem.VirtualInterlining'),
  messageList: Selector('[name="msg"]'),
  messageListOption: Selector('[name="msg"]').find('option'),
  numberOfCodes: Selector('[name="numUsages"]'),
  numberOfCodesLeft: Selector('[name="numUsagesLeft"]'),
  numberOfDiscountRows: Selector('tr.odd'),
  orderNumberInput: Selector('[name="anyRef"]'),
  orderSearchDatePicker: Selector('#datetime_icon_0'),
  orderSearchPreviousMonth: Selector('.ui-icon.ui-icon-circle-triangle-w'),
  orderSearchDoneDateButton: Selector('.ui-datepicker-close'),
  product: Selector('.resultSet:nth-child(2) tbody tr'),
  productPrice: Selector('[name="fullPrice"]'),
  passwordInput: Selector('[name="passWord"]'),
  providerBookingIdLink: Selector(
    '[id*="AirBookings"] .e-tabs-content .e-tabs-tab-content > table > tbody > tr > td:nth-child(2) > a',
  ),
  providerBookingId: Selector(
    '[id*="AirBookings"] .e-tabs-content .e-tabs-tab-content > table > tbody > tr > td:nth-child(2) > span',
  ),
  realDiscountGeneratorButton: Selector('.group.noToggler.left > .button.button-green').nth(1),
  saveProductButton: Selector('[title="Save Product"]'),
  submitButton: Selector('[name="__submit"]'),
  userNameInput: Selector('[name="userName"]'),
  addOnPurchaseButton: Selector('#goToAddOnPurchases'),
  createAddOnCartButton: Selector('#addOnPurchasePlaceholder button').nth(0),
  addOnProductsModal: Selector('.availableAddOnProducts'),
  activatePaymentLinkButton: Selector('footer button').nth(0),
  avaliableAddOnProducts: productNr =>
    Selector(
      `.availableAddOnProducts > div > div > div > div > div:nth-child(${productNr}) .fa.fa-shopping-cart`,
    ),
  activatePaymentLinkTextArea: Selector('[role="dialog"] textarea'),
  createPaymentLinkButton: Selector('div[role="dialog"] > div > div:nth-child(3) button').nth(0),
  paymentLinkSendEmailCheckbox: Selector('div[role="dialog"] form [value="sendEmail"]'),
  paymentLinkCopyToClipboardCheckbox: Selector('div[role="dialog"] form [value="copyToClipboard"]'),
  addOnCartActionsDropdown: Selector('[class*="Droplist__Trigger"]').nth(1),
  copyPaymentLinkSelection: Selector('#uid2 div > span').nth(5),
  orderNotesSelection: Selector('#uid2 div > span').nth(4),
  orderNoteAddButton: Selector('[role="dialog"] button:nth-child(1)'),
  orderNoteTitleInput: Selector('[role="dialog"] [type="text"]'),
};
