import { Selector } from 'testcafe';

export default {
  allProductsInOrder: Selector('[data-testid="cart-content-products"] li'),
  baggageDetails: Selector('[data-testid*="travelerList-segment"]'),
  cabinClassInfo: Selector('[data-testid="tripDetails-segment-cabinClass"]'),
  cartCheckInProduct: Selector('[data-testid="cart-product-onlineCheckIn"]'),
  cartAllInclusiveProduct: Selector('[data-testid="cart-product-allInclusiveProtection"]'),
  cartAllInclusivePrice: Selector('[data-testid="cart-product-allInclusiveProtection-price"]'),
  cartCheckinBaggageProduct: Selector('[data-testid="cart-product-checkInBaggage"]'),
  cartComprehensiveInsuranceCoverGeniusProduct: Selector(
    '[data-testid="cart-product-comprehensiveInsuranceCoverGenius"]',
  ),
  cartItem: Selector('.etiCartItem'),
  cartTagIcon: Selector('[data-testId="cart-tag-icon"]'),
  cartFlexTicketProduct: Selector('[data-testid="cart-product-flexibleTicket"]'),
  cartMobileTravelPlanProduct: Selector('[data-testid="cart-product-mobileTravelPlan"]'),
  cartSmsProduct: Selector('[data-testid="cart-product-sms"]'),
  cartSupportPackageProduct: Selector('[data-testid="cart-product-servicePackage"]'),
  cartTripCancellationProduct: Selector('[data-testid="cart-product-tripCancellationProtection"]'),
  cartTripCancellationPrice: Selector(
    '[data-testid="cart-product-tripCancellationProtection-price"]',
  ),
  cc2cEntries: Selector('[data-testid="cc2carrier-transaction-entry"]'),
  chooseFirstOrderButton: Selector('[data-testid$="-order-button"]'),
  companyInformationAddress: Selector('[data-testid="company.streetAddress-input"]'),
  companyInformationCompanyAddress: Selector('[data-testid="company.companyAddress-input"]'),
  companyInformationCity: Selector('[data-testid="company.city-input"]'),
  companyInformationZipCode: Selector('[data-testid="company.zipCode-input"]'),
  companyInformationName: Selector('[data-testid="company.companyName-input"]'),
  companyInformationVatNumber: Selector('[data-testid="company.vatNumber-input"]'),
  contactPersonEmail: Selector('[data-testid="orderPage-ReceiptInformation-customerEmail"]'),
  discountPrice: Selector('[data-testid="orderPage-discountPrice"]'),
  downloadTripDocument: Selector('[data-testid="traveldoc-link"]'),
  firstBoundPlaneIcon: Selector(
    '[data-testid="tripDetails-bound"]:nth-child(1) [data-testid="tripDetails-bound-plane-icon"]',
  ),
  flightInfoButton: Selector('[data-testid="order-show-flight-info-button"]'),
  infoTextOrderPage: Selector('[data-testid="order-page"] .etiContentWrapper span').nth(0),
  mailConfirmationButton: Selector('[data-testid="mailConfirmation-button"]'),
  moreInfoButton: Selector('[data-testid="order-lccinfo-toggle-button"]'),
  myBookingsButton: Selector('[data-testid="my-bookings-large"]'),
  myBookingsButtonMobile: Selector('[data-testid="myBookings-dropdown-small"]'),
  myBookingsButtonOrderPage: Selector('[data-testid="myBookings-dropdown-large"]'),
  myBookingsEmailInput: Selector('[data-testid="email-input"]'),
  myBookingsOrderNumberInput: Selector('[data-testid="orderNumber-input"]'),
  myBookingsLogInButton: Selector('[data-testid="login-button"]'),
  myBookingsLogOutButton: Selector('[data-testid="myBookings-logout"]'),
  orderInfoTrip: Selector('[data-testid="cart-content-Trip"]'),
  orderNumber: Selector('[data-testid="orderPage-ReceiptInformation-orderNumber"]'),
  orderPage: Selector('[data-testid="order-page"]'),
  owcInformation: Selector('[data-testid="tripDetails-oneWayCombination-wrapper"]'),
  paymentMethod: Selector('[data-testid="cart-content-products"] + div'),
  pdfIframe: Selector('iframe'),
  printConfirmationButton: Selector('[data-testid="printConfirmation-button"]'),
  printBusinessReceiptDropdown: Selector('[data-testid="printable-orders-dropdown"]'),
  printBusinessReceiptButton: Selector('[data-testid="receiptPrintModal-printCompany-button"]'),
  postBookingProducts: Selector('[data-testid="orderPage-postBooking-product"]'),
  postBookingProductsText: Selector('[data-testid="orderPage-postBooking-product"] p'),
  posBookingProductPrice: Selector('[data-testid="orderPage-postBooking-product"]>p:nth-child(2)'),
  postBookingTotalPrice: Selector(
    '[data-testid="orderPage-postBooking-order"] .cart-cartItem-price',
  ),
  receiptInformation: Selector('[data-testid="orderPage-ReceiptInformation-section"]'),
  seatMapProduct: Selector('[data-testid="cart-product-seatMap"]'),
  secondBoundTrainIcon: Selector(
    '[data-testid="tripDetails-bound"]:nth-child(2) [data-testid="tripDetails-bound-train-icon"]',
  ),
  seeAllProductsButton: Selector('[data-testid="order-postBooking-link"]'),
  selfServiceRebookingImage: Selector('[data-testid="image-panel"]'),
  selfServiceRebookingInfoText: Selector(
    '[data-testid="processingOrderPage-description"] p:nth-child(1)',
  ),
  selfServiceRebookingTitle: Selector('[data-testid="processingOrderPage-title"]'),
  selfTransferInformationText: Selector(
    '[data-testid="orderPage-self-guarantee-info-TripNotification"]',
  ),
  selfTransferHeader: Selector('[data-testid="self-transfer-header"]'),
  selfTransferText: Selector('[data-testid="self-transfer-content"]'),
  shortConnectionNotification: Selector('[data-testid="short-connection-time-notification"]'),
  showBaggageButton: Selector('[data-testid="order-show-baggage-info-button"]'),
  stepIndicatorCurrent: Selector('[data-testid="current-step"]'),
  stepIndicatorNotVisited: Selector('[data-testid="not-visited-step"]'),
  stepIndicatorVisited: Selector('[data-testid="visited-step"]'),
  ticketPrice: Selector('[class="cart-cartItem-price"]').nth(0),
  totalPrice: Selector('[data-testid="orderPage-totalPrice"]'),
  trainTripSecondBoundTrainSegmentIcon: Selector(
    '[data-testid="tripDetails-bound"]:nth-child(2) [data-testid="tripDetails-segment-train"]',
  ),
  travelDocumentButton: Selector('[data-testid="traveldoc-link"]'),
  travelerInfo: Selector('[data-testid*="payment-tripdetails-traveler-"]'),
  travelerName: Selector('[data-testid="traveler-name"]'),
  travelerPriceInfo: Selector('[data-testid="traveler-price-info"]'),
  tripBound: Selector('[data-testid="tripDetails-bound"]'),
  tripSegment: Selector('[data-testid="tripDetails-segment"]'),
  tripInformation: Selector('.etiCartContent .etiCartItem'),
  tripInfoText: Selector('[data-testid="tripDetails-segment-event"]'),
  tripSegFirstOrigin: Selector('[data-testid="trip-segment-origin-time"]')
    .nth(0)
    .nextSibling(),
  tripSegSecondOrigin: Selector('[data-testid="trip-segment-origin-time"]')
    .nth(1)
    .nextSibling(),
  tripSegFirstDestination: Selector('[data-testid="trip-segment-destination-time"]')
    .nth(0)
    .nextSibling(),
  tripSegSecondDestination: Selector('[data-testid="trip-segment-destination-time"]')
    .nth(1)
    .nextSibling(),
};
